version: '3.8'

services:
  mongo-0:
    hostname: 'mongodb'
    container_name: 'mongo-0'
    image: 'mongo:5.0.3'
    ports:
      - 27017:27017
    networks:
      - mongors-network
    environment:
      - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
      - MONGO_INITDB_DATABASE=${BASE_MONGO_INITDB_DATABASE}_${BUILD_ENVIRONMENT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    volumes:
      - $PWD/data/mongo-0:/data/db
      - $PWD/scripts/create-user.sh:/docker-entrypoint-initdb.d/create-user.sh
      - $PWD/keyfile/file.key:/auth/file.key
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    restart: always
    links:
      - mongo-1
      - mongo-2
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all",  "--keyFile", "/auth/file.key"]

  mongo-1:
    hostname: 'mongodb'
    container_name: 'mongo-1'
    image: 'mongo:5.0.3'
    ports:
      - 27018:27017
    networks:
      - mongors-network
    volumes:
      - $PWD/data/mongo-1:/data/db
      - $PWD/keyfile/file.key:/auth/file.key
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all",  "--keyFile", "/auth/file.key"]

  mongo-2:
    hostname: 'mongodb'
    container_name: 'mongo-2'
    image: 'mongo:5.0.3'
    ports:
        - 27019:27017
    networks:
      - mongors-network
    volumes:
        - $PWD/data/mongo-2:/data/db
        - $PWD/keyfile/file.key:/auth/file.key
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all",  "--keyFile", "/auth/file.key"]

  mongoclient:
    image: mongo:5.0.3
    networks:
      - mongors-network
    depends_on:
      - mongo-0
      - mongo-1
      - mongo-2
    env_file:
      - .env
    volumes:
      - $PWD/scripts/initiate_replica.sh:/deployment_scripts/initiate_replica.sh
      - $PWD/mongostatus:/data/
    entrypoint:
      - /deployment_scripts/initiate_replica.sh

networks:
  mongors-network:
    driver: bridge